Backend+AK2: misc fixes - fix fallback broken unzip detection now that we create a subdirectory prior - probably best to execute the bump/loki/whatever script using our included ash shell instead of the recovery sh.

diff --git a/packagesm/META-INF/com/google/android/update-binary b/packagesm/META-INF/com/google/android/update-binary
--- a/packagesm/META-INF/com/google/android/update-binary
+++ b/packagesm/META-INF/com/google/android/update-binary
@@ -30,6 +30,9 @@ ui_print " ";
 mkdir -p /tmp/anykernel/bin;
 cd /tmp/anykernel;
 unzip -o "$ZIP";
+if [ $? != 0 -o -z "$(ls /tmp/anykernel/tools)" ]; then
+  abort "Unzip failed. Aborting...";
+fi;
 
 ui_print "$(file_getprop /tmp/anykernel/anykernel.sh kernel.string)";
 ui_print " ";
